# Generated by Django 4.1.7 on 2023-07-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_remove_post_images_image_post_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='public_id',
            field=models.CharField(default='public_ic', max_length=100),
            preserve_default=False,
        ),
    ]
