# Generated by Django 4.1.7 on 2023-05-04 16:58

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_alter_post_image_featuredblog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.path_and_rename.wrapper),
        ),
    ]
